import streamlit as st
import database as db
st.title("PES1UG20CS123")
st.subheader("Aggregate")
import pandas as pd


choice = st.selectbox("Choice",["Aggregate 1","Aggregate 2","Aggregate 3",'Aggregate 4'])

if choice == 'Aggregate 1':
    res = db.agg1()
    st.write("Aggregate function to count the number of complaints of each user")
    with st.expander("View all"):
        df = pd.DataFrame(res,columns = ['User ID','Count of Complaints'])
        st.dataframe(df)

if choice == 'Aggregate 2':
    res = db.agg2()
    st.write("Aggregate function to count the residents of each area")
    with st.expander("View all"):
        df = pd.DataFrame(res,columns = ['Area ID','Count of Residents'])
        st.dataframe(df)

if choice == 'Aggregate 3':
    res = db.agg3()
    st.write("Aggregate function to find maximum weight of non-biodegradable waste generated day-wise")
    with st.expander("View all"):
        df = pd.DataFrame(res,columns = ['Date','User ID','Max Weight of non-bio waste'])
        st.dataframe(df)
    
if choice == 'Aggregate 4':
    res = db.agg4()
    st.write("Aggregate function to find total non-bio and bio waste generated by a user")
    with st.expander("View all"):
        df = pd.DataFrame(res,columns = ['User ID','Total Weight of non-bio waste','Total Weight of bio waste'])
        st.dataframe(df)