name: Push-to-ec2

on:
  push:
    branches: 
      - trial_1
  pull_request:
    branches:
      - trial_1
      
jobs:
  deploy:
    name: Deploy to EC2 on trial_1 branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          script: |
            streamlit run app.py
            
  
  
